# Numpy

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,13,14,15]

In [3]:
arr1 = np.array(list1)

In [4]:
arr2 = np.array([list1,list2,list3])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
type(arr2)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr2.shape

(3, 5)

In [9]:
arr1.ndim

1

In [10]:
arr2.ndim

2

In [11]:
arr1.size

5

In [12]:
arr2.size

15

In [13]:
print(arr2)
arr2.transpose()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [14]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(12,dtype=int,order='C')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

In [16]:
np.ones(12,dtype=int,order='F')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
np.arange(6,100,2,dtype=int)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72,
       74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
np.empty(10,dtype=int)

array([       1,        1,        0,  6619244,      600,        0,
       16777984,    32765,  3997778,       49])

In [20]:
np.linspace(0,100,num=17,dtype=int)

array([  0,   6,  12,  18,  25,  31,  37,  43,  50,  56,  62,  68,  75,
        81,  87,  93, 100])

In [21]:
np.linspace(0,100,num=17,dtype=int,endpoint=False)

array([ 0,  5, 11, 17, 23, 29, 35, 41, 47, 52, 58, 64, 70, 76, 82, 88, 94])

- argsort, which is an indirect sort along a specified axis

- lexsort, which is an indirect stable sort on multiple keys

In [22]:
list1 = [4,5,3,4,5,6,7,6,5,44,3,2,1]

In [23]:
np.sort(list1)

array([ 1,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6,  7, 44])

In [24]:
np.argsort(list1)

array([12, 11,  2, 10,  0,  3,  1,  4,  8,  5,  7,  6,  9], dtype=int64)

In [25]:
np.lexsort(list1)

0

In [26]:
print(list1)
list2

[4, 5, 3, 4, 5, 6, 7, 6, 5, 44, 3, 2, 1]


[6, 7, 8, 9, 10]

In [27]:
np.concatenate((list1,list2))

array([ 4,  5,  3,  4,  5,  6,  7,  6,  5, 44,  3,  2,  1,  6,  7,  8,  9,
       10])

In [28]:
np.array([1,2,3,4,5]).reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
a = np.array([[1,2],[2,3],[4,5]])
a

array([[1, 2],
       [2, 3],
       [4, 5]])

In [30]:
a.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [4],
       [5]])

In [31]:
np.reshape(a,newshape=(1,6))

array([[1, 2, 2, 3, 4, 5]])

convert a 1D array into a 2D array

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [33]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[1 2 3 4 5 6]]


(1, 6)

In [34]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6]]


(1, 6)

In [35]:
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [36]:
b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [37]:
c = np.expand_dims(a, axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

In [38]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [39]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
np.unique(a,return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [41]:
np.array([4,5,'4','5'])

array(['4', '5', '4', '5'], dtype='<U11')

In [42]:
np.unique(np.array([4,5,'4','5']))

array(['4', '5'], dtype='<U11')

In [43]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
y = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
np.hstack((x,y))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [46]:
np.vstack((x,y))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
np.flip(x)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [48]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with formula

 <b> Mean Squared Error </b> = (1 / n) &sum; (y_pred - y)** 2

In [50]:
y_pred = [1,1,1]
n = 3
y = [1,2,3]

In [51]:
mse = (1/n) * np.sum(np.square(np.array(y_pred) - np.array(y)))
print(round(mse,2))

1.67
